name: plyzer-sku
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy
  - pillow
  - pandas
  - opencv

  - pip:
    - opencv-python
    - absl-py==0.9.0
    - astor==0.8.1
    - gast==0.2.2
    - google-pasta==0.1.8
    - grpcio==1.26.0
    - h5py==2.10.0
    - keras==2.2.5
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - keras-resnet==0.2.0
    - markdown==3.1.1
    - numpy==1.18.0
    - opt-einsum==3.1.0
    - protobuf==3.11.2
    - pyyaml==5.2
    - scipy==1.4.1
    - tensorboard==1.15.0
    - tensorflow==1.15.0
    - tensorflow-estimator==1.15.1
    - termcolor==1.1.0
    - tqdm==4.41.0
    - werkzeug==0.16.0
    - wrapt==1.11.2